### ISSUE TITLE
fail build in linux

### ISSUE THREAD

**Issue by sl1pkn07** [VFR-maniac/VapourSynth-TNLMeans#1]
fail build in linux

http://sl1pkn07.wtf/paste/view/d831f07f

need add:

```
using std::ptrdiff_t;
```

in the line 24 in 'AlignedMemory.cpp' between includes and 'namespace AlignedMemory'

I not sure if is a god fix. but with this build OK

greetings

**Comment by 4re** [comment]
For me

```
diff --git a/AlignedMemory.cpp b/AlignedMemory.cpp
index 472908f..47d5156 100644
--- a/AlignedMemory.cpp
+++ b/AlignedMemory.cpp
@@ -18,6 +18,7 @@
  * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
  *****************************************************************************/

+#include <cstddef>
 #include <cassert>
 #include <cstdlib>
```

also solves de problem.

Oh, and on linux I think `-fPIC` flag is also needed, at least it is for me.

**Comment by sl1pkn07** [comment]
yes. need -fPIC (set in --extra-cxxflags). and set executable the configure xd

greetings

EDIT: thanks for the patch, 4re.
 (my "solution" is taken from http://hemanthk.me/wordpress/2014/07/03/error-ptrdiff_t-was-not-declared-in-this-scope/)

**Comment by VFR-maniac** [comment]
Hi.
Thank you for reporting the issue.

How about this?
https://github.com/VFR-maniac/VS-TNLMeans/commit/92af68adaade9c8f514cbc03f6560fbddb2ceb78

**Comment by 4re** [comment]
That fixes the compilation issues for me, thanks!

And not a big deal, but it would be nice to set the executable bit on the _configure_ file too.

**Comment by VFR-maniac** [comment]
Can I close this issue?

P.S. I renamed the name of the repository.

**Comment by sl1pkn07** [comment]
yes. you can close
